URL_CONFIG = [

# ==========================================================================
# 1. RBI & REGULATORY SOURCES (P1: Regulation / Statute, P2: Consumer Guidance)
# ==========================================================================

{
    "label": "01_kfs_circular",
    "url": "https://rbidocs.rbi.org.in/rdocs/notification/PDFs/CIRCULARKFS1504242AE2500BAF494C2A82442B0B642705C1.PDF",
    "type": "pdf",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": ["KFS", "APR", "fees", "repayment", "loan_cost"],
    "document_date": "2024-04-15",
    "last_updated": None,
    "effective_from": "2024-10-01",
    "effective_until": None,
    "applicability_from": "2024-10-01",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "02_rbi_housing_loans_faq",
    "url": "https://rbi.org.in/CommonPerson/english/scripts/FAQs.aspx?Id=701",
    "type": "html",
    "authority": "RBI",
    "source_type": "consumer_guidance",
    "document_scope": "consumer_guidance",
    "priority": 2,
    "product": "home_loan",
    "topics": [
        "home_loan",
        "housing_loan",
        "MITC",
        "loan_terms",
        "prepayment",
        "interest_rate",
        "offer_letter",
        "borrower_rights",
        "reverse_mortgage",
    ],
    "document_date": "2009-11-10",
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "03_prepayment_charges_directions_2025",
    "url": "https://www.rbi.org.in/scripts/NotificationUser.aspx?Id=12878&Mode=0",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": ["prepayment", "foreclosure", "charges", "loan_closure"],
    "document_date": "2025-07-02",
    "last_updated": None,
    "effective_from": "2026-01-01",
    "effective_until": None,
    "applicability_from": "2026-01-01",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "04_interest_rate_on_advances_master_direction",
    "url": "https://rbidocs.rbi.org.in/rdocs/notification/PDFs/MD20D6FC6F31E8E5458F9E0411F433B7D40A.PDF",
    "type": "pdf",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "interest_rate",
        "advances",
        "MCLR",
        "repo_rate",
        "lending_rate",
    ],
    "document_date": "2016-03-03",
    "last_updated": None,
    "effective_from": "2016-03-03",
    "effective_until": None,
    "applicability_from": "2016-03-03",
    "applicability": ["all_commercial_banks"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "05_housing_finance_master_circular",
    "url": "https://rbidocs.rbi.org.in/rdocs/notification/PDFs/NT168E73C887EB7C4C69A01A0F2FB458C9AB.PDF",
    "type": "pdf",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": "home_loan",
    "topics": [
        "housing_finance",
        "home_loan",
        "property",
        "construction",
        "housing_credit",
    ],
    "document_date": "2025-04-01",
    "last_updated": None,
    "effective_from": "2025-04-01",
    "effective_until": None,
    "applicability_from": "2025-04-01",
    "applicability": ["all_commercial_banks"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "06_emi_floating_rate_reset_circular",
    "url": "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12529",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "EMI",
        "floating_rate",
        "interest_reset",
        "personal_loans",
        "fixed_rate_switch",
    ],
    "document_date": "2023-08-18",
    "last_updated": None,
    "effective_from": "2023-08-18",
    "effective_until": None,
    "applicability_from": "2023-12-31",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "07_property_document_release_circular",
    "url": "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12535&Mode=0",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "property_documents",
        "loan_closure",
        "collateral",
        "release_of_documents",
        "compensation",
        "30_day_timeline",
    ],
    "document_date": "2023-09-13",
    "last_updated": None,
    "effective_from": "2023-12-01",
    "effective_until": None,
    "applicability_from": "2023-12-01",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "08_penal_charges_circular",
    "url": "https://rbi.org.in/Scripts/NotificationUser.aspx?Id=12527&Mode=0",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "penal_charges",
        "default",
        "late_payment",
        "penal_interest",
        "MITC",
    ],
    "document_date": "2023-08-18",
    "last_updated": None,
    "effective_from": "2024-04-01",
    "effective_until": None,
    "applicability_from": "2024-04-01",
    "implementation_extension_date": "2023-12-29",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "09_banking_regulation_act_1949",
    "url": "https://www.indiacode.nic.in/handle/123456789/1885",
    "type": "html",
    "authority": "Government of India",
    "source_type": "statute",
    "document_scope": "statute",
    "priority": 1,
    "product": None,
    "topics": [
        "banking_regulation",
        "banking_law",
        "banking_act",
        "regulated_entities",
    ],
    "document_date": "1949-03-10",
    "last_updated": None,
    "effective_from": "1949-03-16",
    "effective_until": None,
    "applicability_from": "1949-03-16",
    "applicability": ["all_banks"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "10_rbi_fair_practices_code_interest_2024",
    "url": "https://www.rbi.org.in/scripts/NotificationUser.aspx?Id=12678&Mode=0",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "fair_practices",
        "interest_charging",
        "loan_disbursement",
        "interest_start_date",
        "disclosure",
        "borrower_protection",
    ],
    "document_date": "2024-04-29",
    "last_updated": None,
    "effective_from": "2024-04-29",
    "effective_until": None,
    "applicability_from": "2024-04-29",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "11_rbi_fair_practices_code",
    "url": "https://www.rbi.org.in/commonman/english/scripts/Notification.aspx?Id=1572",
    "type": "html",
    "authority": "RBI",
    "source_type": "historical_reference",
    "document_scope": "consumer_guidance",
    "priority": 5,
    "product": None,
    "topics": [
        "fair_practices",
        "loan_application",
        "disclosure",
        "grievance",
        "borrower_rights",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "historical_reference",
},

{
    "label": "12_rbi_integrated_ombudsman_scheme_faq",
    "url": "https://www.rbi.org.in/commonperson/english/scripts/FAQs.aspx?Id=3407",
    "type": "html",
    "authority": "RBI",
    "source_type": "consumer_guidance",
    "document_scope": "consumer_guidance",
    "priority": 2,
    "product": None,
    "topics": [
        "complaints",
        "grievance",
        "ombudsman",
        "consumer_protection",
        "bank_complaints",
        "NBFC_complaints",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "13_rbi_kyc_faq_2025",
    "url": "https://www.rbi.org.in/commonperson/english/scripts/FAQs.aspx?Id=3782",
    "type": "html",
    "authority": "RBI",
    "source_type": "consumer_guidance",
    "document_scope": "consumer_guidance",
    "priority": 2,
    "product": None,
    "topics": [
        "KYC",
        "identity",
        "documents",
        "customer_due_diligence",
        "account_update",
    ],
    "document_date": "2025-06-09",
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "14_rbi_kyc_master_direction",
    "url": "https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=11566",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "KYC",
        "master_direction",
        "customer_due_diligence",
        "identity_verification",
        "AML",
        "periodic_updation",
    ],
    "document_date": "2016-02-25",
    "last_updated": "2025-08-14",  # Source: RBI page heading (Updated as on August 14, 2025)
    "effective_from": "2016-02-25",
    "effective_until": None,
    "applicability_from": "2016-02-25",
    "applicability": ["all_rbi_regulated_entities"],  # Direction 2(a): applies to every entity regulated by RBI
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "active",
},

{
    "label": "15_rbi_digital_lending_directions_2025",
    "url": "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12848&Mode=0",
    "type": "html",
    "authority": "RBI",
    "source_type": "regulatory",
    "document_scope": "general_regulation",
    "priority": 1,
    "product": None,
    "topics": [
        "digital_lending",
        "online_loans",
        "LSP",
        "lending_service_provider",
        "KFS",
        "APR",
        "borrower_protection",
        "data_privacy",
        "cooling_off",
        "digital_lending_apps",
    ],
    "document_date": "2025-05-08",
    "last_updated": None,
    "effective_from": "2025-05-08",
    "effective_until": None,
    "applicability_from": "2025-05-08",
    "applicability": ["all_commercial_banks", "nbfcs", "hfcs"],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {
        "para_17_digital_lending_app_reporting": "2025-06-15",
        "para_6_lsp_multiple_re_arrangements": "2025-11-01"
    },  # Source: RBI Digital Lending Directions 2025 commencement provisions
    "status": "active",
},

{
    "label": "16_rbi_secured_assets_sarfaesi_faq",
    "url": "https://www.rbi.org.in/commonperson/english/scripts/FAQs.aspx?Id=3572",
    "type": "html",
    "authority": "RBI",
    "source_type": "consumer_guidance",
    "document_scope": "consumer_guidance",
    "priority": 2,
    "product": "secured_loan",
    "topics": [
        "secured_loan",
        "collateral",
        "SARFAESI",
        "secured_assets",
        "default",
    ],
    "document_date": "2024-02-06",
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

# ==========================================================================
# 2. BANK / HFC PRODUCT-SPECIFIC DOCUMENTS (P4)
# ==========================================================================

{
    "label": "17_icici_emi_upi_mitc",
    "url": "https://www.icici.bank.in/personal-banking/loans/smart-loan/most-important-terms-and-conditions",
    "type": "html",
    "authority": "ICICI Bank",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "EMI @ UPI",
    "topics": [
        "MITC",
        "EMI",
        "charges",
        "interest_rate",
        "default",
        "credit_bureau_reporting",
        "grievance_redressal",
        "compensation_policy",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "18_icici_emi_upi_terms_and_conditions",
    "url": "https://www.icici.bank.in/personal-banking/loans/smart-loan/terms-and-conditions-for-emi-upi",
    "type": "html",
    "authority": "ICICI Bank",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "EMI @ UPI",
    "topics": [
        "MITC",
        "loan_terms",
        "EMI",
        "repayment",
        "default",
        "late_payment",
        "events_of_default",
        "lien",
        "set_off",
        "indemnity",
        "dispute_resolution",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "19_hdfc_home_loan_mitc",
    "url": "https://homeloans.hdfc.bank.in/content/dam/housingdevelopmentfinancecorp/pdf/terms-and-conditions/others/Terms-Conditions-for-HDFC-Bank-Home-Loan.pdf",
    "type": "pdf",
    "authority": "HDFC Bank",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "home_loan",
    "topics": [
        "MITC",
        "home_loan",
        "loan_terms",
        "fees",
        "prepayment",
        "insurance",
        "disbursement",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "20_sbi_home_loan_mitc",
    "url": "https://homeloans.sbi.bank.in/downloads/Terms-and-Conditions.pdf",
    "type": "pdf",
    "authority": "State Bank of India",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "home_loan",
    "topics": [
        "MITC",
        "home_loan",
        "loan_terms",
        "penal_charges",
        "prepayment",
        "fees",
        "default",
        "disclosure",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "21_kotak_personal_loan_mitc",
    "url": "https://www.kotak.bank.in/content/dam/Kotak/Customer-Service/Download-Forms/Personal-Banking/loans/personal_loan/pl-mitc-24oct.pdf",
    "type": "pdf",
    "authority": "Kotak Mahindra Bank",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "personal_loan",
    "topics": [
        "MITC",
        "personal_loan",
        "loan_terms",
        "foreclosure",
        "prepayment",
        "penal_charges",
        "fees",
        "default",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "22_axis_bank_personal_loan_terms_and_conditions",
    "url": "https://www.axis.bank.in/docs/default-source/default-document-library/personal-loans-tc.pdf",
    "type": "pdf",
    "authority": "Axis Bank",
    "source_type": "bank_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "personal_loan",
    "topics": [
        "loan_terms",
        "personal_loan",
        "foreclosure",
        "prepayment",
        "penal_charges",
        "default",
        "NPA",
        "SMA",
        "lien",
        "set_off",
        "arbitration",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "23_bajaj_housing_finance_retail_mitc",
    "url": "https://www.bajajhousingfinance.in/documents/37350/3993180/MITC+-+Retail+(Secured+and+Unsecured)+-+English+(2).pdf",
    "type": "pdf",
    "authority": "Bajaj Housing Finance Limited",
    "source_type": "hfc_product_terms",
    "document_scope": "product_specific",
    "priority": 4,
    "product": "retail_loans",
    "topics": [
        "MITC",
        "HFC",
        "home_loan",
        "loan_against_property",
        "unsecured_loan",
        "prepayment",
        "penal_charges",
        "grievance_redressal",
        "national_housing_bank",
        "fees",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

# ==========================================================================
# 3. CIBIL / CREDIT INFORMATION (P3)
# ==========================================================================

{
    "label": "24_cibil_score_and_report_brochure",
    "url": "https://www.cibil.com/content/dam/cibil/consumer/cibil-score-and-report-brochure-15-10-25.pdf",
    "type": "pdf",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "CIBIL",
        "credit_score",
        "credit_report",
        "credit_information",
        "credit_history",
    ],
    "document_date": "2025-10-15",
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "25_cibil_credit_score_and_loan_basics",
    "url": "https://www.cibil.com/faq/credit-score-and-loan-basics",
    "type": "html",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "credit_score",
        "loan",
        "credit_history",
        "creditworthiness",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "26_cibil_loan_rejections_and_disputes",
    "url": "https://www.cibil.com/faq/loan-rejections-disputes",
    "type": "html",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "loan_rejection",
        "credit_report",
        "disputes",
        "creditworthiness",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "27_cibil_consumer_awareness",
    "url": "https://www.cibil.com/faq/consumer-awareness",
    "type": "html",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "consumer_awareness",
        "credit",
        "loans",
        "credit_report",
        "disputes",
        "enquiries",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "28_cibil_understand_credit_score_and_report",
    "url": "https://www.cibil.com/faq/understand-your-credit-score-and-report",
    "type": "html",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "credit_score",
        "credit_report",
        "credit_history",
        "enquiries",
        "account_information",
        "payment_history",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},

{
    "label": "29_cibil_report_understanding",
    "url": "https://www.cibil.com/content/dam/cibil/consumer/CIBIL-Report-Understanding.pdf",
    "type": "pdf",
    "authority": "TransUnion CIBIL",
    "source_type": "consumer_education",
    "document_scope": "consumer_education",
    "priority": 3,
    "product": None,
    "topics": [
        "credit_report",
        "credit_score",
        "account_information",
        "payment_history",
        "credit_enquiries",
        "overdue",
        "credit_utilisation",
    ],
    "document_date": None,
    "last_updated": None,
    "effective_from": None,
    "effective_until": None,
    "applicability_from": None,
    "applicability": [],
    "supersedes": [],
    "superseded_by": [],
    "special_effective_dates": {},
    "status": "reference",
},
]